# Generated by Django 5.2.10 on 2026-01-12 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('enrollment_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de Matrícula')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Data de Matrícula')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name='Nome do Contato de Emergência')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone do Contato de Emergência')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['-enrollment_date'],
            },
        ),
    ]
