# Generated by Django 5.2.10 on 2026-02-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_preregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preregistration',
            old_name='last_name',
            new_name='responsible_name',
        ),
        migrations.AddField(
            model_name='preregistration',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='cpf',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='family_income',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='gender',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='graduation_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='has_device',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='has_internet',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='household_members',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='how_did_you_hear',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='intended_course',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='previous_vesting',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='pronouns',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='racial_self_declaration',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='responsible_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='rg',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='school_status',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='school_type',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='social_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='state',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='why_join',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='works_currently',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
