# Generated by Django 5.2.12 on 2026-04-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_last_name_preregistration_responsible_name_and_more'),
        ('students', '0008_add_responsible_fields'),
        ('students', '0008_preregistration_responsavel_fields'),
    ]

    operations = [
    ]
