# Generated by Django 5.2.12 on 2026-04-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_student_profile_and_preregistration_alignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preregistration',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='preregistration',
            name='course_interest',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='has_device',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='how_did_you_hear',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='responsible_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='responsible_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='social_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='why_join',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='works_currently',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
