# Generated by Django 5.2.12 on 2026-04-20 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_preregistration_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vestibular', models.CharField(max_length=150, verbose_name='Vestibular')),
                ('institution', models.CharField(max_length=200, verbose_name='Instituição')),
                ('course_name', models.CharField(max_length=200, verbose_name='Curso')),
                ('approval_year', models.PositiveIntegerField(verbose_name='Ano de Aprovação')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_approvals_created', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='students.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Aprovação do Aluno',
                'verbose_name_plural': 'Aprovações dos Alunos',
                'ordering': ['-approval_year', '-created_at'],
            },
        ),
    ]
