# Generated by Django 5.2.12 on 2026-04-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_studentapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistration',
            name='has_private_study_space',
            field=models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='housing_status',
            field=models.CharField(blank=True, choices=[('PROPRIA', 'Moradia própria'), ('ALUGADA', 'Moradia alugada'), ('CEDIDA', 'Moradia cedida'), ('COMPARTILHADA', 'Moradia compartilhada'), ('OUTRA', 'Outra situação')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='receives_social_benefit',
            field=models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='transportation_type',
            field=models.CharField(blank=True, choices=[('A_PE', 'A pé'), ('BICICLETA', 'Bicicleta'), ('ONIBUS', 'Ônibus/transporte público'), ('MOTO', 'Moto'), ('CARRO', 'Carro'), ('OUTRO', 'Outro')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='weekly_study_hours',
            field=models.CharField(blank=True, choices=[('ATE_5', 'Até 5 horas por semana'), ('DE_6_A_10', 'De 6 a 10 horas por semana'), ('DE_11_A_15', 'De 11 a 15 horas por semana'), ('MAIS_15', 'Mais de 15 horas por semana')], default='', max_length=20),
        ),
    ]
