# Generated by Django 5.2.12 on 2026-04-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_preregistration_has_private_study_space_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistration',
            name='responsible_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='responsible_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email do Responsável'),
        ),
        migrations.AddField(
            model_name='student',
            name='responsible_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome do Responsável'),
        ),
        migrations.AddField(
            model_name='student',
            name='responsible_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone do Responsável'),
        ),
    ]
