# Generated by Django 5.2.12 on 2026-04-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_preregistration_responsible_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='responsible_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail do responsável'),
        ),
    ]
