# Generated by Django 5.2.12 on 2026-04-20 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('courses', '0002_discipline_disciplina_carga_horaria_and_more'),
        ('students', '0011_alter_preregistration_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PUBLICADA', 'Publicada'), ('ENCERRADA', 'Encerrada')], default='RASCUNHO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FEZ', 'Fez'), ('NAO_FEZ', 'Não fez'), ('AUSENTE', 'Ausente'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['student_id'],
            },
        ),
        migrations.RenameIndex(
            model_name='submission',
            new_name='assessments_quiz_id_d179eb_idx',
            old_name='assessments__quiz_id_0b0e2d_idx',
        ),
        migrations.AddField(
            model_name='activity',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='courses.disciplina'),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='courses.turma'),
        ),
        migrations.AddField(
            model_name='activityresult',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessments.activity'),
        ),
        migrations.AddField(
            model_name='activityresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_results', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='activityresult',
            unique_together={('activity', 'student')},
        ),
    ]
