# Generated by Django 5.2.12 on 2026-04-20 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_activity_activityresult_and_more'),
        ('courses', '0002_discipline_disciplina_carga_horaria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='courses.areaconhecimento'),
        ),
        migrations.AddField(
            model_name='activity',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_led', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='courses.disciplina'),
        ),
        migrations.AlterField(
            model_name='activityresult',
            name='status',
            field=models.CharField(choices=[('FEZ', 'Fez'), ('ENTREGUE', 'Entregue'), ('NAO_FEZ', 'Não fez'), ('AUSENTE', 'Ausente'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=20),
        ),
    ]
