# Generated by Codex on 2026-04-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_activity_area_activity_teacher_alter_activity_course_and_more'),
        ('courses', '0002_discipline_disciplina_carga_horaria_and_more'),
        ('students', '0013_preregistration_has_private_study_space_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EssaySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('prompt', models.TextField(blank=True)),
                ('essay_text', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='essays/%Y/%m/')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Enviada'), ('UNDER_REVIEW', 'Em correção'), ('CORRECTED', 'Corrigida')], default='SUBMITTED', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('teacher_feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('corrected_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='essay_corrections', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_submissions', to='courses.disciplina')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_submissions', to='students.student')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
