# Generated by Django 5.2.12 on 2026-04-21 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_essaysubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essaysubmission',
            name='attachment',
        ),
        migrations.AddField(
            model_name='activityresult',
            name='corrected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de correção'),
        ),
        migrations.AddField(
            model_name='activityresult',
            name='corrected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_activity_results', to=settings.AUTH_USER_MODEL, verbose_name='Professor responsável'),
        ),
        migrations.AddField(
            model_name='activityresult',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota'),
        ),
        migrations.AddField(
            model_name='activityresult',
            name='submission_url',
            field=models.URLField(blank=True, help_text='Link do Google Docs, Drive, Dropbox ou outra nuvem.', verbose_name='Link de envio'),
        ),
        migrations.AddField(
            model_name='activityresult',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de envio'),
        ),
        migrations.AddField(
            model_name='activityresult',
            name='teacher_feedback',
            field=models.TextField(blank=True, verbose_name='Feedback do professor'),
        ),
        migrations.AddField(
            model_name='essaysubmission',
            name='submission_url',
            field=models.URLField(blank=True, help_text='Link externo da redação no Google Docs, Drive ou outra nuvem.', verbose_name='Link da redação'),
        ),
        migrations.AlterField(
            model_name='activityresult',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observação do aluno'),
        ),
        migrations.AlterField(
            model_name='activityresult',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADA', 'Enviada'), ('EM_CORRECAO', 'Em correção'), ('CORRIGIDA', 'Corrigida'), ('REVISAO_SOLICITADA', 'Revisão solicitada'), ('NAO_ENTREGUE', 'Não entregue'), ('FEZ', 'Fez'), ('ENTREGUE', 'Entregue'), ('NAO_FEZ', 'Não fez'), ('AUSENTE', 'Ausente')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='essaysubmission',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('SUBMITTED', 'Enviada'), ('UNDER_REVIEW', 'Em correção'), ('CORRECTED', 'Corrigida'), ('REVISAO_SOLICITADA', 'Revisão solicitada'), ('NAO_ENTREGUE', 'Não entregue')], default='SUBMITTED', max_length=20),
        ),
    ]
