# Generated by Django 5.2.12 on 2026-04-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_remove_essaysubmission_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PUBLICADA', 'Publicada'), ('ENCERRADA', 'Encerrada')], default='RASCUNHO', max_length=20, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='activityresult',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADA', 'Enviada'), ('EM_CORRECAO', 'Em correção'), ('CORRIGIDA', 'Corrigida'), ('REVISAO_SOLICITADA', 'Revisão solicitada'), ('NAO_ENTREGUE', 'Não entregue'), ('FEZ', 'Fez'), ('ENTREGUE', 'Entregue'), ('NAO_FEZ', 'Não fez'), ('AUSENTE', 'Ausente')], default='PENDENTE', max_length=20, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='essaysubmission',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('SUBMITTED', 'Enviada'), ('UNDER_REVIEW', 'Em correção'), ('CORRECTED', 'Corrigida'), ('REVISAO_SOLICITADA', 'Revisão solicitada'), ('NAO_ENTREGUE', 'Não entregue')], default='SUBMITTED', max_length=20, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Rascunho'), ('SUB', 'Enviado'), ('GRD', 'Corrigido')], default='DRAFT', max_length=5, verbose_name='Situação'),
        ),
    ]
