from django.urls import path
from django.views.generic import RedirectView
from . import views


app_name = 'admin_panel'

urlpatterns = [
    path(
        '',
        views.dashboard,
        name='admin_panel_dashboard',
    ),
    path(
        'dashboard/',
        views.dashboard,
        name='dashboard',
    ),
    path(
        'alunos/',
        views.students_list,
        name='students_list',
    ),
    # alias em português
    path(
        'alunos/',
        views.students_list,
        name='alunos_list',
    ),
    path(
        'alunos/criar/',
        views.student_create,
        name='student_create',
    ),
    path(
        'alunos/<int:student_id>/editar/',
        views.student_edit,
        name='student_edit',
    ),
    path(
        'alunos/<int:student_id>/deletar/',
        views.student_delete,
        name='student_delete',
    ),
    path(
        'professores/',
        views.teachers_list,
        name='teachers_list',
    ),
    # alias em português
    path(
        'professores/',
        views.teachers_list,
        name='professores_list',
    ),
    path(
        'professores/criar/',
        views.teacher_create,
        name='teacher_create',
    ),
    # alias singular em português
    path(
        'professores/criar/',
        views.teacher_create,
        name='professor_create',
    ),
    path(
        'professores/<int:teacher_id>/editar/',
        views.teacher_edit,
        name='teacher_edit',
    ),
    # alias singular em português
    path(
        'professores/<int:teacher_id>/editar/',
        views.teacher_edit,
        name='professor_edit',
    ),
    path(
        'professores/<int:teacher_id>/deletar/',
        views.teacher_delete,
        name='teacher_delete',
    ),
    # alias singular em português
    path(
        'professores/<int:teacher_id>/deletar/',
        views.teacher_delete,
        name='professor_delete',
    ),
    path(
        'disciplinas/',
        views.courses_list,
        name='courses_list',
    ),
    # alias em português
    path(
        'disciplinas/',
        views.courses_list,
        name='disciplinas_list',
    ),
    path(
        'disciplinas/criar/',
        views.course_create,
        name='course_create',
    ),
    # alias singular em português
    path(
        'disciplinas/criar/',
        views.course_create,
        name='disciplina_create',
    ),
    path(
        'disciplinas/<int:course_id>/editar/',
        views.course_edit,
        name='course_edit',
    ),
    # alias singular em português
    path(
        'disciplinas/<int:course_id>/editar/',
        views.course_edit,
        name='disciplina_edit',
    ),
    path(
        'disciplinas/<int:course_id>/deletar/',
        views.course_delete,
        name='course_delete',
    ),
    # alias singular em português
    path(
        'disciplinas/<int:course_id>/deletar/',
        views.course_delete,
        name='disciplina_delete',
    ),
    path(
        'turmas/',
        views.turmas_list,
        name='turmas_list',
    ),
    path(
        'turmas/criar/',
        views.turma_create,
        name='turma_create',
    ),
    path(
        'turmas/<int:turma_id>/editar/',
        views.turma_edit,
        name='turma_edit',
    ),
    path(
        'turmas/<int:turma_id>/deletar/',
        views.turma_delete,
        name='turma_delete',
    ),
    path(
        'turmas/<int:turma_id>/alunos/',
        views.turma_students,
        name='turma_students',
    ),
    path(
        'turmas/matricular/',
        views.turma_enrollment_create,
        name='turma_enrollment_create',
    ),
    path(
        'matriculas/',
        views.enrollments_list,
        name='enrollments_list',
    ),
    # alias em português
    path(
        'matriculas/',
        views.enrollments_list,
        name='matriculas_list',
    ),
    path(
        'matriculas/criar/',
        views.matricula_create,
        name='matricula_create',
    ),
    path(
        'matriculas/nova/',
        views.enrollment_create,
        name='enrollment_create',
    ),
    path(
        'matriculas/<int:enrollment_id>/deletar/',
        views.enrollment_delete,
        name='enrollment_delete',
    ),
    path(
        'matriculas/<int:enrollment_id>/deletar/',
        views.enrollment_delete,
        name='matricula_delete',
    ),
    path(
        'login/',
        RedirectView.as_view(
            pattern_name='accounts:login',
            permanent=False,
        ),
    ),
    path(
        'relatorio/alunos/<int:course_id>/',
        views.relatorio_alunos,
        name='relatorio_alunos',
    ),
    path(
        'relatorio/alunos/<int:course_id>/csv/',
        views.relatorio_alunos_csv,
        name='relatorio_alunos_csv',
    ),
    path(
        'relatorio/alunos/',
        views.relatorio_alunos_geral,
        name='relatorio_alunos_geral',
    ),
    path(
        'relatorio/alunos/csv/',
        views.relatorio_alunos_geral_csv,
        name='relatorio_alunos_geral_csv',
    ),
    path(
        'relatorio/alunos/pdf/',
        views.relatorio_alunos_geral_pdf,
        name='relatorio_alunos_geral_pdf',
    ),
    path(
        'frequencia/',
        views.attendance_sessions_list,
        name='attendance_sessions_list',
    ),
    path(
        'frequencia/criar/',
        views.attendance_session_create,
        name='attendance_session_create',
    ),
    path(
        'frequencia/<int:session_id>/',
        views.attendance_session_detail,
        name='attendance_session_detail',
    ),
    path(
        'diario/',
        views.diary_entries_list,
        name='diary_entries_list',
    ),
    path(
        'diario/criar/',
        views.diary_entry_create,
        name='diary_entry_create',
    ),
    path(
        'diario/<int:entry_id>/editar/',
        views.diary_entry_edit,
        name='diary_entry_edit',
    ),
    path(
        'atividades/',
        views.activities_list,
        name='activities_list',
    ),
    path(
        'atividades/criar/',
        views.activity_create,
        name='activity_create',
    ),
    path(
        'atividades/<int:activity_id>/',
        views.activity_detail,
        name='activity_detail',
    ),
    path(
        'atividades/<int:activity_id>/editar/',
        views.activity_edit,
        name='activity_edit',
    ),
    path(
        'administrativo/',
        views.administrative_list,
        name='administrative_list',
    ),
    path(
        'administrativo/criar/',
        views.administrative_create,
        name='administrative_create',
    ),
    path(
        'comunicacao/emails/',
        views.email_communications_list,
        name='email_communications_list',
    ),
    path(
        'comunicacao/emails/individual/',
        views.email_individual_create,
        name='email_individual_create',
    ),
    path(
        'comunicacao/emails/massa/',
        views.email_bulk_create,
        name='email_bulk_create',
    ),
    path(
        'comunicacao/emails/<int:communication_id>/',
        views.email_communication_detail,
        name='email_communication_detail',
    ),
    path(
        'comunicacao/templates/',
        views.email_templates_list,
        name='email_templates_list',
    ),
    path(
        'comunicacao/templates/criar/',
        views.email_template_create,
        name='email_template_create',
    ),
    path(
        'comunicacao/templates/<int:template_id>/editar/',
        views.email_template_edit,
        name='email_template_edit',
    ),
    path(
        'avisos/',
        views.panel_notices_list,
        name='panel_notices_list',
    ),
    path(
        'avisos/criar/',
        views.panel_notice_create,
        name='panel_notice_create',
    ),
    path(
        'avisos/<int:notice_id>/editar/',
        views.panel_notice_edit,
        name='panel_notice_edit',
    ),
    path(
        'avisos/<int:notice_id>/deletar/',
        views.panel_notice_delete,
        name='panel_notice_delete',
    ),
    path(
        'calendario/',
        views.calendar_events_list,
        name='calendar_events_list',
    ),
    path(
        'calendario/criar/',
        views.calendar_event_create,
        name='calendar_event_create',
    ),
    path(
        'calendario/<int:event_id>/editar/',
        views.calendar_event_edit,
        name='calendar_event_edit',
    ),
    path(
        'calendario/<int:event_id>/deletar/',
        views.calendar_event_delete,
        name='calendar_event_delete',
    ),
    path(
        'pre-cadastros/',
        views.pre_registrations_list,
        name='pre_registrations_list',
    ),
    path(
        'pre-cadastros/<int:preregistration_id>/analisar/',
        views.pre_registration_review,
        name='pre_registration_review',
    ),
    path(
        'blog/',
        views.blog_posts_list,
        name='blog_posts_list',
    ),
    path(
        'blog/criar/',
        views.blog_post_create,
        name='blog_post_create',
    ),
    path(
        'blog/<int:post_id>/editar/',
        views.blog_post_edit,
        name='blog_post_edit',
    ),
    path(
        'blog/<int:post_id>/deletar/',
        views.blog_post_delete,
        name='blog_post_delete',
    ),
    path(
        'links-importantes/',
        views.important_links_list,
        name='important_links_list',
    ),
    path(
        'links-importantes/criar/',
        views.important_link_create,
        name='important_link_create',
    ),
    path(
        'links-importantes/<int:link_id>/editar/',
        views.important_link_edit,
        name='important_link_edit',
    ),
    path(
        'links-importantes/<int:link_id>/deletar/',
        views.important_link_delete,
        name='important_link_delete',
    ),
    path(
        'relatorio/',
        views.relatorio_index,
        name='relatorio_index',
    ),
    path(
        'relatorio/professores/',
        views.relatorio_professores_geral,
        name='relatorio_professores_geral',
    ),
    path(
        'relatorio/professores/csv/',
        views.relatorio_professores_geral_csv,
        name='relatorio_professores_geral_csv',
    ),
    path(
        'relatorio/administrativo/',
        views.relatorio_administrativo_geral,
        name='relatorio_administrativo_geral',
    ),
    path(
        'relatorio/administrativo/csv/',
        views.relatorio_administrativo_geral_csv,
        name='relatorio_administrativo_geral_csv',
    ),
    path(
        'relatorio/alunos/<int:aluno_id>/ficha/',
        views.ficha_aluno,
        name='ficha_aluno',
    ),
    path(
        'relatorio/professores/<int:professor_id>/ficha/',
        views.ficha_professor,
        name='ficha_professor',
    ),
]
