# Generated by Django 5.2.11 on 2026-02-08 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('material_type', models.CharField(choices=[('PDF', 'PDF'), ('DOC', 'Documento Word'), ('SLIDE', 'Apresentação'), ('EXERCISE', 'Lista de Exercícios'), ('OTHER', 'Outro')], default='PDF', max_length=10, verbose_name='Tipo de Material')),
                ('file', models.FileField(upload_to='materials/%Y/%m/', verbose_name='Arquivo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.disciplina', verbose_name='Disciplina')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('platform', models.CharField(choices=[('YOUTUBE', 'YouTube'), ('VIMEO', 'Vimeo'), ('OTHER', 'Outro')], default='YOUTUBE', max_length=10, verbose_name='Plataforma')),
                ('video_url', models.URLField(verbose_name='Link do Vídeo')),
                ('duration', models.CharField(blank=True, help_text='Exemplo: 45 minutos', max_length=20, verbose_name='Duração')),
                ('lesson_number', models.IntegerField(default=0, help_text='Para ordenação', verbose_name='Número da Aula')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_lessons', to='courses.disciplina', verbose_name='Disciplina')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
            ],
            options={
                'verbose_name': 'Aula em Vídeo',
                'verbose_name_plural': 'Aulas em Vídeo',
                'ordering': ['course', 'lesson_number'],
            },
        ),
    ]
