# Generated by Django 5.2.12 on 2026-04-20 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_discipline_disciplina_carga_horaria_and_more'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='external_url',
            field=models.URLField(blank=True, verbose_name='Link Externo'),
        ),
        migrations.AddField(
            model_name='material',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='courses.turma', verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/%Y/%m/', verbose_name='Arquivo'),
        ),
    ]
