# Generated by Django 5.2.12 on 2026-04-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_external_url_material_turma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='file',
        ),
        migrations.AlterField(
            model_name='material',
            name='external_url',
            field=models.URLField(help_text='Link compartilhável do material hospedado em nuvem externa.', verbose_name='Link Externo'),
        ),
    ]
