# Generated by Django 5.2.12 on 2026-04-21 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_seed_enem_areas'),
        ('materials', '0003_remove_material_file_alter_material_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='courses.areaconhecimento', verbose_name='Área de Conhecimento'),
        ),
    ]
