# Generated by Django 5.2.12 on 2026-04-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_material_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='external_url',
            field=models.URLField(help_text='Link compartilhável do material hospedado em nuvem externa.', verbose_name='Link externo'),
        ),
        migrations.AlterField(
            model_name='material',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro'),
        ),
    ]
