# Generated by Django 5.2.12 on 2026-04-21 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('students', '0014_preregistration_responsible_email_and_more'),
        ('teachers', '0003_teacher_knowledge_areas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=180, verbose_name='Assunto')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('send_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('MASSA', 'Em massa')], max_length=20)),
                ('recipient_group', models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('RESPONSAVEL', 'Responsável'), ('ALUNO_RESPONSAVEL', 'Aluno e responsável'), ('TODOS_ALUNOS', 'Todos os alunos'), ('TODOS_PROFESSORES', 'Todos os professores'), ('TODOS_RESPONSAVEIS', 'Todos os responsáveis'), ('ALUNOS_TURMA', 'Alunos de uma turma'), ('PROFESSORES_TURMA', 'Professores de uma turma'), ('ALUNOS_ATIVOS', 'Alunos ativos'), ('ALUNOS_BAIXA_FREQUENCIA', 'Alunos com baixa frequência'), ('ALUNOS_ATIVIDADE_PENDENTE', 'Alunos com atividade pendente')], max_length=40)),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('PARCIAL', 'Parcial'), ('FALHOU', 'Falhou')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('successful_recipients', models.PositiveIntegerField(default=0)),
                ('failed_recipients', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_communications_sent', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Comunicação por Email',
                'verbose_name_plural': 'Comunicações por Email',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailCommunicationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de destino')),
                ('name', models.CharField(blank=True, max_length=180, verbose_name='Nome')),
                ('recipient_type', models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('RESPONSAVEL', 'Responsável')], max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('FALHOU', 'Falhou'), ('SEM_EMAIL', 'Sem email')], default='PENDENTE', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='admin_panel.emailcommunication', verbose_name='Comunicação')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_recipients', to='students.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_recipients', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Destinatário de Email',
                'verbose_name_plural': 'Destinatários de Email',
                'ordering': ['name', 'email'],
            },
        ),
    ]
