# Generated by Django 5.2.12 on 2026-04-21 13:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_emailcommunication_emailcommunicationrecipient'),
        ('courses', '0003_seed_enem_areas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailcommunication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comunicação por Email', 'verbose_name_plural': 'Comunicações por Email'},
        ),
        migrations.AddField(
            model_name='emailcommunication',
            name='category',
            field=models.CharField(choices=[('GERAL', 'Geral'), ('PEDAGOGICO', 'Pedagógico'), ('FREQUENCIA', 'Frequência'), ('ATIVIDADE', 'Atividade'), ('REUNIAO', 'Reunião'), ('EVENTO', 'Evento'), ('ORIENTACAO', 'Orientação'), ('RESPONSAVEL', 'Responsável'), ('PROFESSORES', 'Professores')], default='GERAL', max_length=30, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='emailcommunication',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='emailcommunication',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data agendada'),
        ),
        migrations.AddField(
            model_name='emailcommunication',
            name='send_immediately',
            field=models.BooleanField(default=True, verbose_name='Enviar imediatamente'),
        ),
        migrations.AlterField(
            model_name='emailcommunication',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio'),
        ),
        migrations.AlterField(
            model_name='emailcommunication',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('AGENDADO', 'Agendado'), ('ENVIADO', 'Enviado'), ('PARCIAL', 'Parcial'), ('FALHOU', 'Falhou')], default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('event_type', models.CharField(choices=[('AULA_ESPECIAL', 'Aula especial'), ('SIMULADO', 'Simulado'), ('REVISAO', 'Revisão'), ('REUNIAO', 'Reunião'), ('PRAZO_ATIVIDADE', 'Prazo de atividade'), ('REDACAO', 'Redação'), ('OFICINA', 'Oficina'), ('FERIADO', 'Feriado'), ('INSTITUCIONAL', 'Evento institucional')], default='INSTITUCIONAL', max_length=30, verbose_name='Tipo de evento')),
                ('starts_at', models.DateTimeField(verbose_name='Início')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('location', models.CharField(blank=True, max_length=180, verbose_name='Local')),
                ('audience', models.CharField(choices=[('TODOS', 'Todos'), ('ALUNOS', 'Alunos'), ('PROFESSORES', 'Professores'), ('ADMINISTRATIVO', 'Administrativo')], default='TODOS', max_length=20, verbose_name='Público-alvo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visível no painel/blog')),
                ('external_calendar_id', models.CharField(blank=True, max_length=180, verbose_name='ID externo do calendário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='courses.turma', verbose_name='Turma específica')),
            ],
            options={
                'verbose_name': 'Evento do Calendário',
                'verbose_name_plural': 'Eventos do Calendário',
                'ordering': ['starts_at', 'title'],
            },
        ),
        migrations.AddField(
            model_name='emailcommunication',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_communications', to='admin_panel.calendarevent', verbose_name='Evento relacionado'),
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('category', models.CharField(choices=[('GERAL', 'Geral'), ('PEDAGOGICO', 'Pedagógico'), ('FREQUENCIA', 'Frequência'), ('ATIVIDADE', 'Atividade'), ('REUNIAO', 'Reunião'), ('EVENTO', 'Evento'), ('ORIENTACAO', 'Orientação'), ('RESPONSAVEL', 'Responsável'), ('PROFESSORES', 'Professores')], default='GERAL', max_length=30, verbose_name='Categoria')),
                ('default_subject', models.CharField(max_length=180, verbose_name='Assunto padrão')),
                ('default_body', models.TextField(verbose_name='Corpo padrão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template de Email',
                'verbose_name_plural': 'Templates de Email',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='emailcommunication',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='admin_panel.emailtemplate', verbose_name='Template utilizado'),
        ),
        migrations.CreateModel(
            name='PanelNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Título')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='Resumo')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('category', models.CharField(choices=[('GERAL', 'Geral'), ('PEDAGOGICO', 'Pedagógico'), ('FREQUENCIA', 'Frequência'), ('ATIVIDADE', 'Atividade'), ('REUNIAO', 'Reunião'), ('EVENTO', 'Evento'), ('ORIENTACAO', 'Orientação'), ('RESPONSAVEL', 'Responsável'), ('PROFESSORES', 'Professores')], default='GERAL', max_length=30, verbose_name='Categoria')),
                ('audience', models.CharField(choices=[('TODOS', 'Todos'), ('ALUNOS', 'Alunos'), ('PROFESSORES', 'Professores'), ('ADMINISTRATIVO', 'Administrativo')], default='TODOS', max_length=20, verbose_name='Público-alvo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visível')),
                ('published_at', models.DateTimeField(verbose_name='Data de publicação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_notices_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_notices', to='courses.turma', verbose_name='Turma específica')),
            ],
            options={
                'verbose_name': 'Aviso do Painel',
                'verbose_name_plural': 'Avisos do Painel',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='related_notice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='admin_panel.panelnotice', verbose_name='Aviso relacionado'),
        ),
        migrations.AddField(
            model_name='emailcommunication',
            name='related_notice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_communications', to='admin_panel.panelnotice', verbose_name='Aviso relacionado'),
        ),
    ]
