# Generated by Django 5.2.12 on 2026-04-21 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_emailcommunication_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailcommunication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comunicação por E-mail', 'verbose_name_plural': 'Comunicações por E-mail'},
        ),
        migrations.AlterModelOptions(
            name='emailcommunicationrecipient',
            options={'ordering': ['name', 'email'], 'verbose_name': 'Destinatário de E-mail', 'verbose_name_plural': 'Destinatários de E-mail'},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Modelo de E-mail', 'verbose_name_plural': 'Modelos de E-mail'},
        ),
        migrations.AlterField(
            model_name='emailcommunication',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('AGENDADO', 'Agendado'), ('ENVIADO', 'Enviado'), ('PARCIAL', 'Parcial'), ('FALHOU', 'Falhou')], default='PENDENTE', max_length=20, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='emailcommunication',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='admin_panel.emailtemplate', verbose_name='Modelo utilizado'),
        ),
        migrations.AlterField(
            model_name='emailcommunicationrecipient',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail de destino'),
        ),
        migrations.AlterField(
            model_name='emailcommunicationrecipient',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('FALHOU', 'Falhou'), ('SEM_EMAIL', 'Sem e-mail')], default='PENDENTE', max_length=20),
        ),
    ]
