# Generated by Django 5.2.11 on 2026-02-08 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('LINGUAGENS', 'Linguagens, Códigos e suas Tecnologias'), ('HUMANAS', 'Ciências Humanas e suas Tecnologias'), ('NATUREZA', 'Ciências da Natureza e suas Tecnologias'), ('MATEMATICA', 'Matemática e suas Tecnologias'), ('REDACAO', 'Redação')], max_length=100, unique=True)),
                ('cor_identificacao', models.CharField(default='#007bff', max_length=7)),
            ],
            options={
                'verbose_name': 'Área de Conhecimento',
                'verbose_name_plural': 'Áreas de Conhecimento',
            },
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, max_length=50)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='courses.areaconhecimento')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.disciplina', verbose_name='Disciplina'),
        ),
    ]
