# Generated by Django 5.2.11 on 2026-02-08 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_areaconhecimento_alter_course_unique_together_and_more'),
        ('materials', '0002_alter_material_course_alter_videolesson_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
