# Generated by Django 5.2.10 on 2026-01-12 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('category', models.CharField(choices=[('NEWS', 'Notícia'), ('ANNOUNCEMENT', 'Aviso'), ('CONTENT', 'Conteúdo Preparatório'), ('EVENT', 'Evento'), ('TIP', 'Dica de Estudo')], default='NEWS', max_length=15, verbose_name='Categoria')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('excerpt', models.TextField(blank=True, help_text='Breve descrição do post (aparece na listagem)', max_length=300, verbose_name='Resumo')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/', verbose_name='Imagem Destaque')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('views_count', models.IntegerField(default=0, verbose_name='Visualizações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Post do Blog',
                'verbose_name_plural': 'Posts do Blog',
                'ordering': ['-publish_date'],
            },
        ),
    ]
