# Generated by Django 5.2.12 on 2026-04-20 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Título')),
                ('url', models.URLField(verbose_name='Link')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('category', models.CharField(choices=[('MEC', 'MEC'), ('BOOKS', 'Livros e Bibliotecas'), ('EXAMS', 'Vestibulares e ENEM'), ('STUDY', 'Estudos e Plataformas'), ('OTHER', 'Outro')], default='MEC', max_length=20, verbose_name='Categoria')),
                ('icon', models.CharField(blank=True, help_text='Exemplo: bi-book ou bi-globe', max_length=40, verbose_name='Ícone Bootstrap')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='important_links_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Link Importante',
                'verbose_name_plural': 'Links Importantes',
                'ordering': ['-is_featured', 'display_order', 'title'],
            },
        ),
    ]
