# Generated by Django 5.2.12 on 2026-04-20 22:33

from django.db import migrations


def seed_important_links(apps, schema_editor):
    ImportantLink = apps.get_model('blog', 'ImportantLink')
    links = [
        {
            'title': 'Ministério da Educação - Portal MEC',
            'url': 'https://www.gov.br/mec/pt-br',
            'description': 'Portal oficial do Ministério da Educação com programas, notícias e serviços.',
            'category': 'MEC',
            'icon': 'bi-buildings',
            'is_featured': True,
            'display_order': 1,
        },
        {
            'title': 'Plataforma MEC RED',
            'url': 'https://plataformaintegrada.mec.gov.br/',
            'description': 'Ambiente com recursos educacionais digitais e conteúdos de apoio ao estudo.',
            'category': 'MEC',
            'icon': 'bi-journal-bookmark',
            'is_featured': True,
            'display_order': 2,
        },
        {
            'title': 'Domínio Público',
            'url': 'http://www.dominiopublico.gov.br/',
            'description': 'Biblioteca digital com livros, obras literárias e materiais de acesso público.',
            'category': 'BOOKS',
            'icon': 'bi-book',
            'is_featured': True,
            'display_order': 3,
        },
        {
            'title': 'INEP - ENEM',
            'url': 'https://www.gov.br/inep/pt-br/areas-de-atuacao/avaliacao-e-exames-educacionais/enem',
            'description': 'Informações oficiais do ENEM, cronogramas e orientações aos estudantes.',
            'category': 'EXAMS',
            'icon': 'bi-mortarboard',
            'is_featured': True,
            'display_order': 4,
        },
    ]

    for link in links:
        ImportantLink.objects.update_or_create(
            title=link['title'],
            defaults=link,
        )


def unseed_important_links(apps, schema_editor):
    ImportantLink = apps.get_model('blog', 'ImportantLink')
    ImportantLink.objects.filter(
        title__in=[
            'Ministério da Educação - Portal MEC',
            'Plataforma MEC RED',
            'Domínio Público',
            'INEP - ENEM',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_importantlink'),
    ]

    operations = [
        migrations.RunPython(seed_important_links, unseed_important_links),
    ]
