# Generated by Django 5.2.12 on 2026-04-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_seed_important_links'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date'], 'verbose_name': 'Publicação do Blog', 'verbose_name_plural': 'Publicações do Blog'},
        ),
    ]
