# Generated by Django 5.2.10 on 2026-01-12 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Especialização')),
                ('bio', models.TextField(blank=True, verbose_name='Biografia')),
                ('education', models.TextField(blank=True, verbose_name='Formação Acadêmica')),
                ('experience_years', models.IntegerField(default=0, verbose_name='Anos de Experiência')),
                ('professional_email', models.EmailField(blank=True, max_length=254, verbose_name='Email Profissional')),
                ('lattes_url', models.URLField(blank=True, verbose_name='Link do Currículo Lattes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('hire_date', models.DateField(auto_now_add=True, verbose_name='Data de Contratação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'ordering': ['-hire_date'],
            },
        ),
    ]
