# Generated by Django 5.2.12 on 2026-04-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='availability',
            field=models.TextField(blank=True, verbose_name='Disponibilidade'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='contact_notes',
            field=models.TextField(blank=True, verbose_name='Observações de Contato'),
        ),
    ]
