# Generated by Django 5.2.12 on 2026-04-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_discipline_disciplina_carga_horaria_and_more'),
        ('teachers', '0002_teacher_availability_teacher_contact_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='knowledge_areas',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='courses.areaconhecimento', verbose_name='Áreas do Conhecimento'),
        ),
    ]
