# Generated by Django 5.2.12 on 2026-04-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_knowledge_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='professional_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail profissional'),
        ),
    ]
