# Generated by Django 5.2.11 on 2026-02-08 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConhecimento',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'nome',
                    models.CharField(
                        max_length=100,
                        unique=True,
                        choices=[
                            (
                                'LINGUAGENS',
                                'Linguagens, Códigos e suas Tecnologias',
                            ),
                            (
                                'HUMANAS',
                                'Ciências Humanas e suas Tecnologias',
                            ),
                            (
                                'NATUREZA',
                                'Ciências da Natureza e suas Tecnologias',
                            ),
                            (
                                'MATEMATICA',
                                'Matemática e suas Tecnologias',
                            ),
                            ('REDACAO', 'Redação'),
                        ],
                    ),
                ),
                (
                    'cor_identificacao',
                    models.CharField(
                        default='#007bff',
                        max_length=7,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Área de Conhecimento',
                'verbose_name_plural': 'Áreas de Conhecimento',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, max_length=50)),
                (
                    'area',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='disciplinas',
                        to='courses.areaconhecimento',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'enrollment_date',
                    models.DateField(
                        auto_now_add=True,
                        verbose_name='Data de Matrícula',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        verbose_name='Ativa',
                    ),
                ),
                (
                    'notes',
                    models.TextField(
                        blank=True,
                        verbose_name='Observações',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='Criado em',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name='Atualizado em',
                    ),
                ),
                (
                    'course',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='enrollments',
                        to='courses.disciplina',
                        verbose_name='Disciplina',
                    ),
                ),
                (
                    'student',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='enrollments',
                        to='students.student',
                        verbose_name='Aluno',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['-enrollment_date'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
