# Generated by Django 5.2.12 on 2026-04-20 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0011_alter_preregistration_options_and_more'),
        ('teachers', '0002_teacher_availability_teacher_contact_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('courses.disciplina',),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.PositiveIntegerField(default=0, verbose_name='Carga Horária'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='conteudo_programatico',
            field=models.TextField(blank=True, verbose_name='Conteúdo Programático'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='courses', to='teachers.teacher', verbose_name='Professores'),
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da Turma')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('turno', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite'), ('INTEGRAL', 'Integral')], default='NOITE', max_length=20, verbose_name='Turno')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('EM_ANDAMENTO', 'Em andamento'), ('ENCERRADA', 'Encerrada'), ('INATIVA', 'Inativa')], default='EM_ANDAMENTO', max_length=20, verbose_name='Situação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('disciplines', models.ManyToManyField(blank=True, related_name='turmas', to='courses.disciplina', verbose_name='Disciplinas')),
                ('teachers', models.ManyToManyField(blank=True, related_name='turmas', to='teachers.teacher', verbose_name='Professores')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['-ano', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='courses.turma', verbose_name='Turma'),
        ),
        migrations.CreateModel(
            name='TurmaEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateField(auto_now_add=True, verbose_name='Ingresso')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollments', to='students.student', verbose_name='Aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollments', to='courses.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Matrícula em Turma',
                'verbose_name_plural': 'Matrículas em Turmas',
                'ordering': ['-joined_at'],
                'unique_together': {('student', 'turma')},
            },
        ),
        migrations.AddField(
            model_name='turma',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='turmas', through='courses.TurmaEnrollment', to='students.student', verbose_name='Alunos'),
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('nome', 'ano')},
        ),
    ]
