# Generated by Django 5.2.12 on 2026-04-20 22:21

from django.db import migrations


def seed_enem_areas(apps, schema_editor):
    AreaConhecimento = apps.get_model('courses', 'AreaConhecimento')
    default_areas = [
        ('LINGUAGENS', '#ef6c00'),
        ('MATEMATICA', '#1565c0'),
        ('NATUREZA', '#2e7d32'),
        ('HUMANAS', '#6a1b9a'),
        ('REDACAO', '#c62828'),
    ]

    for nome, cor_identificacao in default_areas:
        AreaConhecimento.objects.update_or_create(
            nome=nome,
            defaults={'cor_identificacao': cor_identificacao},
        )


def unseed_enem_areas(apps, schema_editor):
    AreaConhecimento = apps.get_model('courses', 'AreaConhecimento')
    AreaConhecimento.objects.filter(
        nome__in=['LINGUAGENS', 'MATEMATICA', 'NATUREZA', 'HUMANAS', 'REDACAO']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_discipline_disciplina_carga_horaria_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_enem_areas, unseed_enem_areas),
    ]
