# Generated by Django 5.2.11 on 2026-02-08 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_alias'),
        ('courses', '0003_delete_course'),
    ]

    operations = [
    ]
