# Generated by Django 5.2.11 on 2026-02-08 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_merge'),
        ('courses', '0004_merge_0002_course_alias_0003_delete_course'),
    ]

    operations = [
    ]
