# Generated by Django 5.2.12 on 2026-04-20 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('courses', '0002_discipline_disciplina_carga_horaria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='content_taught',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='courses.turma'),
        ),
        migrations.CreateModel(
            name='ClassDiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da Aula')),
                ('content', models.TextField(verbose_name='Conteúdo Ministrado')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='courses.disciplina', verbose_name='Disciplina')),
                ('session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_entry', to='attendance.attendancesession', verbose_name='Sessão de Frequência')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_diary_entries', to=settings.AUTH_USER_MODEL, verbose_name='Professor Responsável')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='courses.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Diário de Turma',
                'verbose_name_plural': 'Diários de Turma',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
