# Generated by Django 5.2.12 on 2026-04-20 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancesession_content_taught_and_more'),
        ('courses', '0002_discipline_disciplina_carga_horaria_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='courses.areaconhecimento'),
        ),
        migrations.AddField(
            model_name='classdiaryentry',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_entries', to='courses.areaconhecimento', verbose_name='Área do Conhecimento'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='courses.disciplina'),
        ),
        migrations.AlterField(
            model_name='classdiaryentry',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='courses.disciplina', verbose_name='Disciplina'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('turma', 'course', 'date')},
        ),
    ]
